# Wrapper that pins the Semgrep version. Override SEMGREP_RULES at build
# time to bake in a ruleset for air-gapped operation.
FROM semgrep/semgrep:1.84

LABEL org.opencontainers.image.source="https://github.com/ruslanmv/SelfRepair"
LABEL org.opencontainers.image.description="Semgrep SAST scanner for SelfRepair"
LABEL org.opencontainers.image.licenses="Apache-2.0"

WORKDIR /in
ENTRYPOINT []
