"""Publisher: orchestrates the publish step of a repair.

Flow:
    1. Run gitleaks against the workspace; abort on hit.
    2. Create branch, stage, commit.
    3. Sign the commit blob via Sigstore (best-effort unless required).
    4. Push branch (and create PR via gh CLI when `open_pr=True`).
    5. Look up CODEOWNERS for touched files; request as reviewers.

This is the only code that performs side-effects on the remote git host.
The state machine transitions PUBLISHING → AWAITING_REVIEW only after this
function returns successfully; failures escalate.
"""
from __future__ import annotations

import logging
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from selfrepair.git.codeowners import (
    find_codeowners,
    owners_for,
    parse as parse_codeowners,
)
from selfrepair.git.gitleaks import scan_repo as gitleaks_scan
from selfrepair.git.pr_builder import PRBodyContext, render_pr_body
from selfrepair.git.sigstore import Signature, sign_blob
from selfrepair.sdk.models import Finding, Patch, RepairPlan

logger = logging.getLogger(__name__)


class GitleaksTripped(RuntimeError):
    """Raised when gitleaks finds a secret in the diff. Abort the repair."""


@dataclass(frozen=True)
class PublishResult:
    branch: str
    commit_sha: str
    pr_url: str | None
    requested_reviewers: tuple[str, ...]
    signature: Signature | None


def publish_repair(
    *,
    workspace: Path,
    patch: Patch,
    plan: RepairPlan,
    finding: Finding,
    branch_name: str,
    base_branch: str = "main",
    rationale: str = "",
    fail_on_missing_signing: bool = False,
    open_pr: bool = True,
) -> PublishResult:
    scan = gitleaks_scan(workspace)
    if scan.findings:
        secrets = ", ".join(
            f"{f.file_path}:{f.line} ({f.rule_id})" for f in scan.findings
        )
        raise GitleaksTripped(f"secrets detected in diff: {secrets}")

    _git(["checkout", "-B", branch_name], cwd=workspace)
    _git(["add", "-A"], cwd=workspace)
    commit_msg = (
        f"fix: {plan.summary}\n\n"
        f"Finding: {finding.kind}\n"
        f"Fixer: {plan.fixer_id}"
    )
    _git(["commit", "-m", commit_msg], cwd=workspace)
    commit_sha = _git(["rev-parse", "HEAD"], cwd=workspace).stdout.decode().strip()

    blob_path = workspace / ".selfrepair-commit.txt"
    blob_path.write_text(commit_sha, encoding="utf-8")
    signature = sign_blob(blob_path)
    blob_path.unlink(missing_ok=True)
    if signature is None and fail_on_missing_signing:
        raise RuntimeError(
            "sigstore signing required but cosign is not available"
        )

    requested_reviewers: tuple[str, ...] = ()
    codeowners_path = find_codeowners(workspace)
    if codeowners_path:
        rules = parse_codeowners(codeowners_path.read_text(encoding="utf-8"))
        requested_reviewers = tuple(
            sorted(owners_for(list(patch.files_changed), rules))
        )

    pr_url: str | None = None
    if open_pr:
        _git(["push", "-u", "origin", branch_name], cwd=workspace)
        body = render_pr_body(
            PRBodyContext(
                finding=finding,
                plan=plan,
                files_changed=patch.files_changed,
                summary=plan.summary,
                rationale=rationale or "Auto-repair generated by SelfRepair.",
                commit_sha=commit_sha,
                provenance={
                    "builder": "selfrepair",
                    "run_id": "n/a",
                    "run_url": "",
                    "materials_hash": commit_sha,
                    "signed": signature is not None,
                },
            )
        )
        pr_url = _open_pr(
            workspace=workspace,
            base_branch=base_branch,
            head_branch=branch_name,
            title=f"fix: {plan.summary}",
            body=body,
            reviewers=requested_reviewers,
        )

    return PublishResult(
        branch=branch_name,
        commit_sha=commit_sha,
        pr_url=pr_url,
        requested_reviewers=requested_reviewers,
        signature=signature,
    )


def _git(args: list[str], *, cwd: Path) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True
    )


def _open_pr(
    *,
    workspace: Path,
    base_branch: str,
    head_branch: str,
    title: str,
    body: str,
    reviewers: tuple[str, ...],
) -> str | None:
    """Open a PR via the gh CLI. Returns the PR URL on success, None on failure.

    Shells out to `gh` because PyGithub doesn't cleanly cover all the
    GitHub App auth paths. If `gh` isn't installed the publisher logs a
    warning and returns None — the branch is still pushed.
    """
    if shutil.which("gh") is None:
        logger.warning("gh CLI not installed; skipping PR creation")
        return None

    cmd = [
        "gh", "pr", "create",
        "--base", base_branch,
        "--head", head_branch,
        "--title", title,
        "--body", body,
    ]
    if reviewers:
        clean = [r.lstrip("@") for r in reviewers]
        cmd.extend(["--reviewer", ",".join(clean)])

    try:
        completed = subprocess.run(
            cmd, cwd=workspace, check=True, capture_output=True
        )
    except subprocess.CalledProcessError as exc:
        logger.error(
            "gh pr create failed: %s",
            exc.stderr.decode("utf-8", errors="replace"),
        )
        return None
    return completed.stdout.decode("utf-8").strip() or None
