"""Makefile fixer: ensure install / test / start targets exist.

Handles two finding kinds:
  - makefile_missing          → create a fresh Makefile
  - makefile_targets_missing  → append missing targets
"""
from __future__ import annotations

from dataclasses import dataclass

from selfrepair.fixers._diff import make_unified_diff, read_existing
from selfrepair.sdk.models import (
    Finding,
    Patch,
    RepairPlan,
    RepoContext,
    Severity,
)

_DEFAULT_MAKEFILE = """\
# Generated by SelfRepair. Edit safely; run `make help` to list targets.

.PHONY: help install test start

help: ## List available targets
\t@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \\
\t  | awk 'BEGIN {FS = \":.*?## \"}; {printf \"  %-20s %s\\n\", $$1, $$2}'

install: ## Install project dependencies
\tpython -m pip install -e \".[dev]\"

test: ## Run the test suite
\tpytest -q

start: ## Start the application
\t@echo \"Define your start command in the Makefile\"
"""

_REQUIRED_TARGETS: tuple[str, ...] = ("install", "test", "start")

_TARGET_STUBS: dict[str, str] = {
    "install": (
        "install: ## Install project dependencies\n"
        "\tpython -m pip install -e \".[dev]\""
    ),
    "test": (
        "test: ## Run the test suite\n"
        "\tpytest -q"
    ),
    "start": (
        "start: ## Start the application\n"
        "\t@echo \"Define your start command\""
    ),
}


@dataclass(frozen=True)
class MakefileFixer:
    id: str = "py.makefile"
    handles: tuple[str, ...] = (
        "makefile_missing",
        "makefile_targets_missing",
    )
    risk: Severity = Severity.LOW

    def matches(self, finding: Finding, ctx: RepoContext) -> bool:
        return finding.kind in self.handles

    def plan(self, finding: Finding, ctx: RepoContext) -> RepairPlan:
        summary = (
            "Create a Makefile with install/test/start targets"
            if finding.kind == "makefile_missing"
            else "Add missing Makefile targets"
        )
        return RepairPlan(
            fixer_id=self.id,
            finding=finding,
            summary=summary,
            risk=self.risk,
            files_touched=("Makefile",),
        )

    def apply(self, plan: RepairPlan, ctx: RepoContext) -> Patch:
        before = read_existing(ctx.workspace, "Makefile")
        if not before.strip():
            after = _DEFAULT_MAKEFILE
        else:
            missing = _missing_targets(before)
            after = (
                before.rstrip() + "\n\n" + _stub_targets(missing) + "\n"
                if missing
                else before
            )
        diff = make_unified_diff(
            file_path="Makefile", before=before, after=after
        )
        return Patch(
            fixer_id=self.id,
            finding_fingerprint=plan.finding.fingerprint,
            diff=diff,
            files_changed=("Makefile",) if diff else (),
            summary=plan.summary,
        )


def _missing_targets(content: str) -> tuple[str, ...]:
    return tuple(t for t in _REQUIRED_TARGETS if not _has_target(content, t))


def _has_target(content: str, target: str) -> bool:
    prefix = f"{target}:"
    for line in content.splitlines():
        if line.strip().startswith(prefix):
            return True
    return False


def _stub_targets(targets: tuple[str, ...]) -> str:
    parts = ["# Targets added by SelfRepair"]
    parts.extend(_TARGET_STUBS[t] for t in targets if t in _TARGET_STUBS)
    return "\n\n".join(parts)
