FROM aquasec/trivy:0.50.0

LABEL org.opencontainers.image.source="https://github.com/ruslanmv/SelfRepair"
LABEL org.opencontainers.image.description="Trivy SCA + secret + config scanner for SelfRepair"
LABEL org.opencontainers.image.licenses="Apache-2.0"

WORKDIR /in
ENTRYPOINT []
